backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  # Homepage content
  - name: "homepage"
    label: "Homepage"
    file: "content/home.json"
    fields:
      - {label: "Hero Image", name: "hero_image", widget: "image"}

  # Executive board members
  - name: "leadership"
    label: "Executive Board"
    folder: "content/leadership"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Major & Grad Year", name: "details", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}

  # Other leadership positions
  - name: "other_positions"
    label: "Other Leadership Positions"
    file: "content/other_positions.json"
    fields:
      - label: "Positions"
        name: "positions"
        widget: "list"
        fields:
          - {label: "Role", name: "role", widget: "string"}
          - {label: "Name", name: "name", widget: "string"}

  # Rush flyer & header
  - name: "rush_flyer"
    label: "Rush Flyer"
    file: "content/rush_flyer.json"
    fields:
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Flyer Image", name: "flyer_image", widget: "image"}

  # Rush chair info
  - name: "rush_info"
    label: "Rush Information"
    file: "content/rush_info.json"
    fields:
      - {label: "Rush Chair", name: "rush_chair", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Phone", name: "phone", widget: "string"}
      - {label: "Office Hours", name: "office_hours", widget: "string"}

  # Chapter contact info
  - name: "contact"
    label: "Contact Information"
    file: "content/contact.json"
    fields:
      - {label: "Chapter Address", name: "address", widget: "text"}
      - {label: "Main Phone", name: "main_phone", widget: "string"}
      - {label: "General Email", name: "general_email", widget: "string"}
